# Server Port
server.port=8080

# Supabase Storage Configuration
# IMPORTANT: The key below should be the PUBLIC ANON KEY for security reasons.
supabase.url=https://mcsghbpmypfymimfflgq.supabase.co
supabase.anon-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jc2doYnBteXBmeW1pbWZmbGdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0Nzc0MDAsImV4cCI6MjA5MTA1MzQwMH0.Sb6wPojllb7em3mjOGTtqy8UhEpYBiFVKpCPoVKq1v4

# PostgreSQL / Supabase Configuration
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.mcsghbpmypfymimfflgq
spring.datasource.password=UtccRecom2026
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

# JPA / Hibernate
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.open-in-view=false

# Jackson — serialize dates as ISO strings
spring.jackson.serialization.write-dates-as-timestamps=false

# Google Gemini API Key
gemini.api-key=AIzaSyC4Var0dAtTEgHRuSMam8Hx-5fcuSH3-nU