# Server Port
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://bavonvit99_db_user:<ใส่รหัสผ่านของคุณตอนสร้าง-ลบวงเล็บทิ้งด้วย>@utccrecom.hunztjs.mongodb.net/utcc_recom?retryWrites=true&w=majority&appName=UTCCRECOM
